// blogData.js (or whatever filename you prefer)
const data = [
  {
    id: 1,
    image: "..Images/gallery/2.jpg", // Removed require() - will be handled by your build system
    desc: "Home",
    auther: "Beatriz",
    read: "5 min read",
    postedDate: "7 hours ago",
    title: "TAAJ PALACE",
    text: "ABC Banquet Hall is a premier event venue, perfect for hosting a wide range of events, including weddings, corporate events, social gatherings, cultural celebrations, and more. Our spacious banquet hall can accommodate up to 300 guests and is equipped with state-of-the-art lighting and sound systems, ensuring that your event is a success. As the owner of ABC Banquet Hall, I take pride in providing our clients with exceptional service and attention to detail. Our team of experienced event planners will work with you to create a customized menu, decor, and entertainment to make your event unforgettable. Our venue is conveniently located with ample parking, making it easy for your guests to attend.             ",
  },
  {
    id: 2,
    desc: "Love",
    auther: "Charles",
    read: "4 min read",
    postedDate: "1 day ago",
    title: "Star Banquet",
    text: "Welcome to The Star Banquet, the ultimate event venue for weddings, corporate events, social gatherings, and more. Our stunning ballroom can accommodate up to 500 guests and is equipped with the latest technology in lighting and sound. Our experienced event planners will work with you to create a customized menu, decor, and entertainment to make your event unforgettable. With over 10 years of experience, The Grand Ballroom is the perfect choice for your next event.",
    image: "../Images/3.jpg",
  },
  {
    id: 3,
    desc: "Listen",
    auther: "Fatima",
    read: "9 min read",
    postedDate: "Feb 13",
    title: "Smart Palace",
    text: " The Smart Palace is a beautiful outdoor event venue, perfect for hosting weddings, corporate events, and social gatherings. Our lush garden setting can accommodate up to 200 guests and is equipped with a state-of-the-art sound system and lighting. Our experienced event planners will work with you to create a customized menu and decor, ensuring that your event is a reflection of your personal style. With over 20 years of experience, The Garden Terrace is the perfect choice for your next outdoor event.",
    image: "../Images/gallery/4.jpg",
  },
  {
    id: 4,
    desc: "Listen",
    auther: "Gabriel",
    read: "8 min read",
    postedDate: "Feb 10",
    title: "Mystic Mountain",
    text: "Step into Mystic Mountain and experience elegance and luxury like never before. Our sophisticated event venue can accommodate up to 350 guests and is equipped with a stunning crystal chandelier, creating the perfect ambiance for your event. Our experienced event planners will work with you to create a customized menu, decor, and entertainment that suits your style and preferences. With over 15 years of experience, The Crystal Room is the perfect choice for your next upscale event.",
    image: "../Images/gallery/7.jpg",
  },
  {
    id: 5,
    desc: "Home",
    auther: "Hanna",
    read: "3 min read",
    postedDate: "Feb 9",
    title: "Park Village Resort",
    text: "The Park Village Resort is a breathtaking waterfront event venue, perfect for weddings, corporate events, and social gatherings. Our panoramic views of the harbor create the perfect backdrop for your event, while our spacious ballroom can accommodate up to 400 guests. Our experienced event planners will work with you to create a customized menu and decor, ensuring that your event is a reflection of your personal style. With over 10 years of experience, The Harbor View is the perfect choice for your next waterfront event.",
    image: "../Images/gallery/8.jpg",
  },
  {
    id: 6,
    desc: "Listen",
    read: "6 min read",
    postedDate: "Feb 6",
    title: "Hotel Yak & Yeti",
    text: "Step into Hotel Yak & Yeti and experience the magic of an outdoor event. Our beautiful pavilion can accommodate up to 500 guests and is equipped with state-of-the-art lighting and sound systems. Our experienced event planners will work with you to create a customized menu, decor, and entertainment that suits your style and preferences. With over 5 years of experience, The Starlight Pavilion is the perfect choice for your next outdoor event.",
    image: "../Images/gallery/9.jpg",
  },
  {
    id: 7,
    desc: "Listen",
    read: "6 min read",
    postedDate: "Feb 6",
    title: "Chandragiri Resort",
    text: "The Chandragiri Resort is a stunning event venue, perfect for hosting weddings, corporate events, and social gatherings. Our historic building has been transformed into a modern event space, complete with the latest technology in lighting and sound. Our experienced event planners will work with you to create a customized menu and decor, ensuring that your event is a reflection of your personal style. With over 20 years of experience, The Renaissance Hall is the perfect choice for your next event.",
    image: "../Images/gallery/10.jpg",
  },
];

export default data;